### ISSUE TITLE
Address already in use problem in arm-none-eabi-gdb GDB

### ISSUE THREAD

**Issue by ernotormikoski** [ARMmbed/example-mbedos-blinky#9] opened 2015-10-27 09:52 UTC
When trying Debugging applications compiled with GCC (yt debug example-mbedos-blinky) following error comes: error: [Errno 98] Address already in use
When pressing enter gdb starts after error and debuggin can be done normally.

[gdb_debug_issue.txt](https://github.com/ARMmbed/example-mbedos-blinky/files/21556/gdb_debug_issue.txt)

**Comment by 0xc0170** [comment] 2015-10-27 09:58
Thanks for reporting. The issue is tracked in valinor, https://github.com/ARMmbed/valinor/issues/16, please follow that one.

I'll close this one.

**Closed by 0xc0170** 2015-10-27 09:58 UTC

**Comment by autopulated** [comment] 2015-10-30 09:55
(this was fixed in pyOCD 0.6.1, please run `pip install -U pyOCD` to update to that version)
